apiVersion: v1
kind: Service
metadata:
  name: lsd-backend
  namespace: lsd-payments
  labels:
    app: lsd-backend
spec:
  selector:
    app: lsd-backend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
