apiVersion: constraints.gatekeeper.sh/v1beta1
kind: BlockPrivileged
metadata:
  name: block-privileged
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
      - kube-system
      - gatekeeper-system
      - argocd
      - external-secrets
