apiVersion: dynatrace.com/v1beta4
kind: DynaKube
metadata:
  name: lsd-payments
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/automatic-kubernetes-api-monitoring: "true"
spec:
  apiUrl: https://uah28430.live.dynatrace.com/api
  tokens: dynatrace-tokens
  oneAgent:
    classicFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
